services:
  db:
    image: postgres:latest
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: budget_app
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - '4000:4000'
    environement:
      DATABASE_HOST: db
      DATABASE_NAME: budget_app
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    volumes:
      - ./api:/app
    depends_on:
      - db

volumes:
  pgdata: {}
